"""empty message

Revision ID: 96d8f0895133
Revises: b1ada5b0743d
Create Date: 2025-08-24 08:50:12.868471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d8f0895133'
down_revision = 'b1ada5b0743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_memory', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('max_memory')
        batch_op.drop_column('max_time')

    # ### end Alembic commands ###
